# -*- coding: utf-8 -*-
"""task 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iTsWzpJf9VWQVtMLljle-xI82LYxBLUw
"""

# ============================================
# IMAGE CLASSIFICATION USING CNN (TENSORFLOW)
# ============================================

# Step 1: Import Required Libraries
import tensorflow as tf
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
import numpy as np

# ============================================
# Step 2: Load Dataset (CIFAR-10)
# ============================================
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

# Normalize pixel values
x_train = x_train / 255.0
x_test = x_test / 255.0

print("Training data shape:", x_train.shape)
print("Test data shape:", x_test.shape)

# ============================================
# Step 3: Define Class Names
# ============================================
class_names = ['airplane','automobile','bird','cat','deer',
               'dog','frog','horse','ship','truck']

# ============================================
# Step 4: Build CNN Model
# ============================================
model = models.Sequential()

model.add(layers.Conv2D(32, (3,3), activation='relu',
                         input_shape=(32,32,3)))
model.add(layers.MaxPooling2D((2,2)))

model.add(layers.Conv2D(64, (3,3), activation='relu'))
model.add(layers.MaxPooling2D((2,2)))

model.add(layers.Conv2D(64, (3,3), activation='relu'))

model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))

model.summary()

# ============================================
# Step 5: Compile Model
# ============================================
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# ============================================
# Step 6: Train Model
# ============================================
history = model.fit(
    x_train, y_train,
    epochs=10,
    validation_data=(x_test, y_test)
)

# ============================================
# Step 7: Evaluate Model
# ============================================
test_loss, test_acc = model.evaluate(x_test, y_test)
print("\nTest Accuracy:", test_acc)

# ============================================
# Step 8: Plot Accuracy Graph
# ============================================
plt.figure()
plt.plot(history.history['accuracy'], label='Train Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend()
plt.show()

# ============================================
# Step 9: Predictions Example
# ============================================
predictions = model.predict(x_test)

def show_prediction(index):
    plt.imshow(x_test[index])
    plt.title("Predicted: {} | Actual: {}".format(
        class_names[np.argmax(predictions[index])],
        class_names[y_test[index][0]]
    ))
    plt.axis('off')
    plt.show()

# Show sample prediction
show_prediction(0)

# ============================================
# Step 10: Save Model
# ============================================
model.save("cnn_image_classifier.h5")
print("Model saved successfully!")