# -*- coding: utf-8 -*-
"""Task 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HszkiR_StBbeaRmFJEd17JoPYROHn2nW
"""

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import re
import nltk
from nltk.corpus import stopwords

nltk.download('stopwords')
data = {
    "review": [
        "This product is amazing and works great",
        "Worst purchase I ever made",
        "Very happy with the quality",
        "Terrible experience, not recommended",
        "Excellent performance and good value",
        "Completely useless item",
        "Loved it, will buy again",
        "Waste of money",
        "Very satisfied with the service",
        "Bad quality and poor performance"
    ],
    "sentiment": [1,0,1,0,1,0,1,0,1,0]
}

df = pd.DataFrame(data)
stop_words = set(stopwords.words('english'))

def preprocess(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return " ".join(words)

df["clean_review"] = df["review"].apply(preprocess)
X_train, X_test, y_train, y_test = train_test_split(
    df["clean_review"],
    df["sentiment"],
    test_size=0.2,
    random_state=42
)
vectorizer = TfidfVectorizer()
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)
model = LogisticRegression()
model.fit(X_train_tfidf, y_train)
y_pred = model.predict(X_test_tfidf)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
sample_review = ["The product quality is excellent and amazing"]
sample_clean = [preprocess(r) for r in sample_review]
sample_vec = vectorizer.transform(sample_clean)
prediction = model.predict(sample_vec)

print("\nSample Review Prediction:",
      "Positive" if prediction[0]==1 else "Negative")